fn main() {
    windows::build!(
        Windows::Win32::FileSystem::{
            SetFileCompletionNotificationModes,
            CreateIoCompletionPort,
            GetQueuedCompletionStatus
        },
        Windows::Win32::SystemServices::{
            CancelThreadpoolIo,
            CloseThreadpoolIo,
            CreateThreadpoolIo,
            INVALID_HANDLE_VALUE,
            OVERLAPPED,
            StartThreadpoolIo,
            TP_CALLBACK_INSTANCE,
            TP_IO,
        },
        Windows::Win32::WinSock::{
            LPFN_ACCEPTEX,
            LPFN_GETACCEPTEXSOCKADDRS,
            setsockopt,
            WSA_ERROR,
            WSABUF,
            WSAGetLastError,
            WSAIoctl,
            WSARecv,
            WSASend,
            WSASocketW,
        },
        Windows::Win32::Debug::{
            GetLastError,
            WIN32_ERROR,
        },
        Windows::Win32::WindowsProgramming::CloseHandle,
    );
}
