fn main() {
    windows::build!(
        windows::win32::file_system::{
            SetFileCompletionNotificationModes,
            CreateIoCompletionPort,
            GetQueuedCompletionStatus
        },
        windows::win32::system_services::{
            CancelThreadpoolIo,
            CloseThreadpoolIo,
            CreateThreadpoolIo,
            ERROR_IO_PENDING,
            OVERLAPPED,
            StartThreadpoolIo,
            TP_CALLBACK_INSTANCE,
            TP_IO,
        },
        windows::win32::win_sock::{
            LPFN_ACCEPTEX,
            LPFN_GETACCEPTEXSOCKADDRS,
            setsockopt,
            WSABUF,
            WSAGetLastError,
            WSAIoctl,
            WSARecv,
            WSASend,
            WSASocketW,
        },
        windows::win32::debug::GetLastError,
        windows::win32::windows_programming::CloseHandle,
    );
}
